version: "3.8"

services:
  # Dependencies
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-tarragon-postgres}
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 1s
      interval: 1s
      retries: 60
      timeout: 5s
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}

  tarragon:
    build: .
    container_name: ${TARRAGON_CONTAINER_NAME:-tarragon}
    env_file:
      - .env
    ports:
      - ${TARRAGON_PORT:-4000}:${TARRAGON_PORT:-4000}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
